markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
permalink: pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
gems:
  - jekyll-redirect-from
exclude: 
  - CNAME
  - Gemfile
  - README.md
baseurl: https://microsoft.github.io/prose
Title: Microsoft Program Synthesis using Examples SDK

theme: jekyll-theme-cayman